### ISSUE TITLE
False positive `DjangoReadOnlyError` when using `QuerySet.union` and `Queryset.intersection` methods

### ISSUE THREAD

**Issue by kevinmarsh** [adamchainz/django-read-only#166]
### Python Version

3.10.5

### Django Version

4.0.6

### Package Version

1.9.0

### Description

Just ran into a false positive `DjangoReadOnlyError` when I was using [Django's `QuerySet.intersection` method](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#intersection). Eg. on Postgres (maybe other dbs) it creates SQL like

```python
>>> from django.contrib.sites.models import Site
>>> site_ids = Site.objects.values("id").order_by()
>>> print(site_ids.union(site_ids).query)
(SELECT "django_site"."id" FROM "django_site") UNION (SELECT "django_site"."id" FROM "django_site")
>>> print(site_ids.intersection(site_ids).query)
(SELECT "django_site"."id" FROM "django_site") INTERSECT (SELECT "django_site"."id" FROM "django_site")

```

Meaning that the `should_block` function returns `True` since the statement starts with `(` and not `SELECT`

Could fix by either stripping the `(` prefix from `sql` or adding `(SELECT` to the list of allowed prefixes, but there might be a bit more robust approach.

---

Presumably this would be a failing test:
```python
    def test_disable_writes_allows_intersection_and_union_selects(self):
        django_read_only.disable_writes()

        Site.objects.union(Site.objects.all()).count()
        Site.objects.intersection(Site.objects.all()).count()
```

**Comment by adamchainz** [comment]
I've released a fix in 1.10.0. I think it should be safe to skip opening parentheses, and space and newlines.
