### ISSUE TITLE
Adding django-read-only to INSTALLED_APPS causing strange wrapper behavior

### ISSUE THREAD

**Issue by christianbundy** [adamchainz/django-read-only#180]
### Python Version

3.10

### Django Version

4.1

### Package Version

1.10

### Description

Hey @adamchainz -- thanks for all of your work on this project, and in the Django ecosystem in general. I'm hopeful that this is a real defect in django-read-only that we can fix, but I'm open to the idea that I'm holding it wrong. 🙃 

After installing django-read-only, we noticed that our custom query logger seemed to be reporting an every-increasing number of queries per HTTP request. We had `DJANGO_READ_ONLY = False`, but just the presence of `"django_read_only"` in `INSTALLED_APPS` seemed to cause this problem. Reverting the commit that added django-read-only resolved this problem.

I've been banging my head against this for a few days, and I think I have a minimal reproduction. I don't have a great mechanism of action, but I've written a test that:

- usually passes, but
- fails as soon as we add django-read-only to `INSTALLED_APPS`

I don't _think_ I'm doing anything obviously wrong below, but I'd love a second pair of eyees

```python3
from concurrent.futures import ThreadPoolExecutor
from django.db import connection
from django.contrib.auth.models import User


class QueryLogger:
    queries: list[str]

    def __init__(self):
        self.queries = []

    def __call__(self, execute, sql, params, many, context) -> None:
        self.queries.append(sql)
        return execute(sql, params, many, context)


def count_users(n) -> tuple[int, QueryLogger]:
    query_logger = QueryLogger()
    with connection.execute_wrapper(query_logger):
        User.objects.count()
    User.objects.count()  # BUG: This query is seen by query_logger when django-read-only is in INSTALLED_APPS.
    return n, query_logger


def test_threading_query_wrapper_bug():
    thread_count = 1
    expected_queries = 1
    with ThreadPoolExecutor(max_workers=thread_count) as executor:
        results = executor.map(count_users, range(thread_count))
    expected = [(n, expected_queries) for n in range(thread_count)]
    actual = [(n, len(query_logger.queries)) for n, query_logger in results]
    print(f"{expected=}")
    print(f"{actual=}")
    assert expected == actual


test_threading_query_wrapper_bug()
```

The important part is here:

```python3
with connection.execute_wrapper(query_logger):
        User.objects.count()
    User.objects.count()
```

My expectation would be that `query_logger` only sees one query, but when we install django-read-only then it sees _both_ queries. I'd love confirmation whether:

- This would be a defect, not just me misunderstanding the documentation, and
- That you can also reproduce this error, it's not just a quirk of my Django config somehow

I'd push a failing test to CI, but I've gotta head out of town today. Let me know if I can add any other info!

**Comment by adamchainz** [comment]
The issue seems to be due to using `execute_wrapper()` as the thing that auto-creates the database connection. The `QueryLogger` gets inserted into `connection.execute_wrappers` before the `connection_created` signal is fired, meaning django-read-only was adding its instrumentation afterwards. This meant that the exit of `execute_wrapper` would drop django-read-only's `blocker` function instead of the `QueryLogger`.

Fixed in #181, released in 1.10.1.
